[general]
import = ["~/.config/alacritty/themes/themes/breeze.toml"]

[window]
decorations = "Buttonless"
opacity = 0.7
blur = true 
option_as_alt = "OnlyLeft"

[colors]
draw_bold_text_with_bright_colors = true

[terminal]
[terminal.shell]
program = "tmux"

[font]
size = 11

[scrolling]
history = 10000
multiplier = 3
