[theme]
background = "default"
primary = "#DFBEB0"
secondary = "#B37840"
title = "#FF9100"
playing = "#F7A97A"
playing_selected = "#EFDDD3"
playing_bg = "default"
highlight = "#B9461D"
highlight_bg = "default"
error = "#414868"
error_bg = "#f7768e"
statusbar = "#ff9e64"
statusbar_progress = "#E5CBBC"
statusbar_bg = "default"
cmdline = "#c0caf5"
cmdline_bg = "default"
search_match = "#f7768e"
